import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { performance } from "node:perf_hooks";
import { AssetCondition, AssetStatus, PrismaClient } from "@prisma/client";

const baseUrl = process.env.BASE_URL || "http://localhost:5011";
const artifactsDir = path.resolve("tests/artifacts");
const prisma = new PrismaClient();
const zeroUuid = "00000000-0000-0000-0000-000000000000";
const results = [];
const performanceObservations = [];
const state = {};

const ensureArtifactsDir = () => fs.mkdirSync(artifactsDir, { recursive: true });

const seedDatabase = () => {
  execFileSync("npm", ["run", "seed"], { cwd: process.cwd(), env: process.env, stdio: "inherit" });
};

const writeJson = (fileName, payload) => {
  ensureArtifactsDir();
  fs.writeFileSync(path.join(artifactsDir, fileName), `${JSON.stringify(payload, null, 2)}\n`);
};

const escapeMd = (value) => String(value ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");

const record = (endpoint, check, expectedStatus, actualStatus, pass, rootCause = "") => {
  results.push({
    endpoint,
    check,
    expectedStatus,
    actualStatus,
    result: pass ? "PASS" : "FAIL",
    rootCause
  });
};

const request = async (method, pathName, { token, body } = {}) => {
  const headers = { Accept: "application/json" };
  if (body !== undefined) headers["Content-Type"] = "application/json";
  if (token) headers.Authorization = `Bearer ${token}`;

  const startedAt = performance.now();
  const response = await fetch(`${baseUrl}${pathName}`, {
    method,
    headers,
    body: body === undefined ? undefined : JSON.stringify(body)
  });
  const durationMs = Math.round(performance.now() - startedAt);

  let json = null;
  try {
    json = await response.json();
  } catch {
    json = null;
  }

  performanceObservations.push({ endpoint: `${method} ${pathName}`, status: response.status, durationMs });
  return { status: response.status, json };
};

const expectStatus = (method, pathName, check, expectedStatus, response, predicate = () => true) => {
  const pass = response.status === expectedStatus && predicate(response.json);
  record(
    `${method} ${pathName}`,
    check,
    expectedStatus,
    response.status,
    pass,
    pass ? "" : "Expected status and response contract did not match."
  );
};

const login = async (email, password = "password123") => {
  const response = await request("POST", "/api/auth/login", { body: { email, password } });
  if (response.status !== 200) {
    throw new Error(`Login failed for ${email}: HTTP ${response.status}`);
  }
  return response.json.data.token;
};

const items = (payload) => payload?.data?.items ?? payload?.data ?? [];
const isPaginated = (payload) =>
  Boolean(payload?.success === true && Array.isArray(payload?.data?.items) && typeof payload?.data?.total === "number");

const createAsset = async (suffix, departmentId = state.itDepartmentId, status = AssetStatus.AVAILABLE) => {
  if (status === AssetStatus.AVAILABLE) {
    const response = await request("POST", "/api/assets", {
      token: state.adminToken,
      body: {
        assetTag: `MNT-QA-${suffix}`,
        serialNumber: `MNT-QA-SN-${suffix}`,
        name: `Maintenance QA Asset ${suffix}`,
        categoryId: state.laptopCategoryId,
        departmentId,
        condition: "GOOD",
        location: "Maintenance QA Lab"
      }
    });
    if (response.status !== 201) throw new Error(`Failed to create maintenance QA asset: HTTP ${response.status}`);
    return response.json.data;
  }

  return prisma.asset.create({
    data: {
      assetCode: `MNT-QA-${suffix}`,
      serialNumber: `MNT-QA-SN-${suffix}`,
      name: `Maintenance QA Asset ${suffix}`,
      categoryId: state.laptopCategoryId,
      departmentId,
      status,
      condition: AssetCondition.GOOD,
      location: "Maintenance QA Lab",
      createdById: state.adminId,
      updatedById: state.adminId
    }
  });
};

const createMaintenance = async (assetId, token = state.employeeToken, issueSummary = `Maintenance issue ${Date.now()}`) =>
  request("POST", "/api/maintenance", {
    token,
    body: {
      assetId,
      priority: "HIGH",
      issueSummary,
      issueDescription: "Generated by maintenance QA."
    }
  });

const getSeedContext = async () => {
  state.adminToken = await login("admin@assetflow.local");
  state.managerToken = await login("manager@assetflow.local");
  state.employeeToken = await login("employee@assetflow.local");
  state.auditorToken = await login("auditor@assetflow.local");

  const users = await request("GET", "/api/users", { token: state.adminToken });
  const userItems = items(users.json);
  state.adminId = userItems.find((user) => user.email === "admin@assetflow.local")?.id;
  state.managerId = userItems.find((user) => user.email === "manager@assetflow.local")?.id;
  state.employeeId = userItems.find((user) => user.email === "employee@assetflow.local")?.id;

  const departments = await request("GET", "/api/departments", { token: state.adminToken });
  const departmentItems = items(departments.json);
  state.itDepartmentId = departmentItems.find((department) => department.code === "IT")?.id;
  state.operationsDepartmentId = departmentItems.find((department) => department.code === "OPS")?.id;

  const categories = await request("GET", "/api/categories", { token: state.adminToken });
  const categoryItems = items(categories.json);
  state.laptopCategoryId = categoryItems.find((category) => category.code === "LAP")?.id;
};

const writeReport = () => {
  const rows = results
    .map(
      (result) =>
        `| ${escapeMd(result.endpoint)} | ${escapeMd(result.check)} | ${result.expectedStatus} | ${result.actualStatus} | ${result.result} | ${escapeMd(result.rootCause || "None observed.")} |`
    )
    .join("\n");

  const perfRows = performanceObservations
    .filter((entry) => entry.endpoint.includes("/api/maintenance") || entry.endpoint.includes("/api/reports/maintenance") || entry.endpoint.includes("/api/dashboard"))
    .slice(-80)
    .map((entry) => `| ${escapeMd(entry.endpoint)} | ${entry.status} | ${entry.durationMs} ms |`)
    .join("\n");

  const failed = results.filter((result) => result.result === "FAIL").length;
  const report = `# Maintenance QA Report

Generated: ${new Date().toISOString()}

## Summary

| Metric | Value |
| --- | ---: |
| Checks | ${results.length} |
| Passed | ${results.length - failed} |
| Failed | ${failed} |

## Endpoints Covered

- \`GET /api/maintenance\`
- \`GET /api/maintenance/:id\`
- \`POST /api/maintenance\`
- \`PATCH /api/maintenance/:id\`
- \`DELETE /api/maintenance/:id\`
- \`PATCH /api/maintenance/:id/approve\`
- \`PATCH /api/maintenance/:id/reject\`
- \`PATCH /api/maintenance/:id/assign\`
- \`PATCH /api/maintenance/:id/start\`
- \`PATCH /api/maintenance/:id/resolve\`
- \`PATCH /api/maintenance/:id/close\`
- \`GET /api/reports/maintenance\`

## Checks Performed

| Endpoint | Check | Expected Status | Actual Status | Result | Root Cause |
| --- | --- | ---: | ---: | --- | --- |
${rows}

## Performance Observations

| Request | Status | Duration |
| --- | ---: | ---: |
${perfRows}

## Business Rules Verified

- Maintenance endpoints require authentication and role scope.
- Employees can create and read their own tickets.
- Managers can manage tickets only for their department.
- Auditors are read-only.
- Duplicate and active maintenance tickets are rejected.
- Retired and lost assets cannot enter maintenance.
- Invalid lifecycle transitions are rejected.
- Tickets cannot start without technician assignment.
- Resolved/closed workflows restore asset state.
- Notifications and audit logs are generated.

## Known Limitations

- The backend keeps legacy \`OPEN\` support; new requests use \`REQUESTED\`.
- Asset under-maintenance state is represented by the existing \`MAINTENANCE\` asset status.
- There is no scheduled preventive-maintenance calendar in the hackathon MVP.
`;

  fs.writeFileSync(path.join(artifactsDir, "maintenance-qa-report.md"), report);
};

const refreshMaintenanceResponse = async () => {
  const adminToken = await login("admin@assetflow.local");
  const list = await request("GET", "/api/maintenance?page=1&limit=5", { token: adminToken });
  const ticket = list.json?.data?.items?.[0];
  const detail = ticket ? await request("GET", `/api/maintenance/${ticket.id}`, { token: adminToken }) : null;
  const [report, dashboard] = await Promise.all([
    request("GET", "/api/reports/maintenance", { token: adminToken }),
    request("GET", "/api/dashboard/overview", { token: adminToken })
  ]);

  writeJson("maintenance-response.json", {
    list: list.json,
    detail: detail?.json ?? null,
    report: report.json,
    dashboard: dashboard.json
  });
};

const runChecks = async () => {
  await getSeedContext();
  const stamp = Date.now();

  expectStatus("GET", "/api/maintenance", "Maintenance list requires authentication", 401, await request("GET", "/api/maintenance"));
  expectStatus("GET", "/api/maintenance", "Admin can list maintenance tickets", 200, await request("GET", "/api/maintenance", { token: state.adminToken }), isPaginated);
  expectStatus("GET", "/api/maintenance", "Auditor can list maintenance read-only", 200, await request("GET", "/api/maintenance", { token: state.auditorToken }), isPaginated);

  const mainAsset = await createAsset(`${stamp}-MAIN`);
  const createBlocked = await request("POST", "/api/maintenance", {
    token: state.auditorToken,
    body: { assetId: mainAsset.id, priority: "HIGH", issueSummary: "Blocked auditor request" }
  });
  expectStatus("POST", "/api/maintenance", "Auditor cannot create maintenance", 403, createBlocked);

  const created = await createMaintenance(mainAsset.id, state.employeeToken, "Primary maintenance QA issue");
  expectStatus("POST", "/api/maintenance", "Employee can create own maintenance ticket", 201, created, (payload) => payload?.data?.status === "REQUESTED" && payload?.data?.assetId === mainAsset.id);
  state.mainTicketId = created.json?.data?.id;

  const assetInMaintenance = await request("GET", `/api/assets/${mainAsset.id}`, { token: state.adminToken });
  expectStatus("GET", "/api/assets/:id", "Creating maintenance moves asset to maintenance", 200, assetInMaintenance, (payload) => payload?.data?.status === "MAINTENANCE");

  expectStatus("POST", "/api/maintenance", "Duplicate active maintenance is rejected", 409, await createMaintenance(mainAsset.id, state.employeeToken, "Primary maintenance QA issue"));
  expectStatus("POST", "/api/maintenance", "Invalid maintenance payload is rejected", 400, await request("POST", "/api/maintenance", {
    token: state.employeeToken,
    body: { assetId: mainAsset.id, priority: "INVALID", issueSummary: "x" }
  }));
  expectStatus("POST", "/api/maintenance", "Unknown asset returns not found", 404, await request("POST", "/api/maintenance", {
    token: state.employeeToken,
    body: { assetId: zeroUuid, priority: "HIGH", issueSummary: "Unknown asset issue" }
  }));

  const lostAsset = await createAsset(`${stamp}-LOST`, state.itDepartmentId, AssetStatus.LOST);
  expectStatus("POST", "/api/maintenance", "Lost assets cannot enter maintenance", 409, await createMaintenance(lostAsset.id, state.employeeToken, "Lost asset issue"));
  const retiredAsset = await createAsset(`${stamp}-RETIRED`, state.itDepartmentId, AssetStatus.RETIRED);
  expectStatus("POST", "/api/maintenance", "Retired assets cannot enter maintenance", 409, await createMaintenance(retiredAsset.id, state.employeeToken, "Retired asset issue"));

  expectStatus("GET", "/api/maintenance/:id", "Employee can fetch own maintenance ticket", 200, await request("GET", `/api/maintenance/${state.mainTicketId}`, { token: state.employeeToken }), (payload) => payload?.data?.reportedBy?.id === state.employeeId);
  expectStatus("GET", "/api/maintenance/:id", "Missing maintenance ticket returns not found", 404, await request("GET", `/api/maintenance/${zeroUuid}`, { token: state.adminToken }));
  expectStatus("GET", "/api/maintenance/:id", "Invalid maintenance UUID is rejected", 400, await request("GET", "/api/maintenance/not-a-uuid", { token: state.adminToken }));
  expectStatus("PATCH", "/api/maintenance/:id", "Employee cannot update maintenance ticket", 403, await request("PATCH", `/api/maintenance/${state.mainTicketId}`, {
    token: state.employeeToken,
    body: { priority: "CRITICAL" }
  }));

  expectStatus("PATCH", "/api/maintenance/:id", "Admin can update maintenance metadata", 200, await request("PATCH", `/api/maintenance/${state.mainTicketId}`, {
    token: state.adminToken,
    body: { priority: "CRITICAL", issueDescription: "Escalated by QA." }
  }), (payload) => payload?.data?.priority === "CRITICAL");
  expectStatus("PATCH", "/api/maintenance/:id/approve", "Manager can approve department maintenance", 200, await request("PATCH", `/api/maintenance/${state.mainTicketId}/approve`, {
    token: state.managerToken,
    body: { decisionNotes: "Approved by QA" }
  }), (payload) => payload?.data?.status === "APPROVED");
  expectStatus("PATCH", "/api/maintenance/:id/approve", "Maintenance cannot be approved twice", 409, await request("PATCH", `/api/maintenance/${state.mainTicketId}/approve`, {
    token: state.managerToken,
    body: { decisionNotes: "Should fail" }
  }));
  expectStatus("PATCH", "/api/maintenance/:id/reject", "Approved maintenance cannot be rejected", 409, await request("PATCH", `/api/maintenance/${state.mainTicketId}/reject`, {
    token: state.managerToken,
    body: { decisionNotes: "Should fail" }
  }));
  expectStatus("PATCH", "/api/maintenance/:id/start", "Cannot start without technician assignment", 409, await request("PATCH", `/api/maintenance/${state.mainTicketId}/start`, {
    token: state.managerToken,
    body: {}
  }));
  expectStatus("PATCH", "/api/maintenance/:id/assign", "Manager can assign technician", 200, await request("PATCH", `/api/maintenance/${state.mainTicketId}/assign`, {
    token: state.managerToken,
    body: { assignedTechnicianId: state.managerId }
  }), (payload) => payload?.data?.status === "ASSIGNED" && payload?.data?.assignedTechnicianId === state.managerId);
  expectStatus("PATCH", "/api/maintenance/:id/start", "Manager can start assigned maintenance", 200, await request("PATCH", `/api/maintenance/${state.mainTicketId}/start`, {
    token: state.managerToken,
    body: {}
  }), (payload) => payload?.data?.status === "IN_PROGRESS" && Boolean(payload?.data?.startedAt));
  expectStatus("PATCH", "/api/maintenance/:id/resolve", "Manager can resolve in-progress maintenance", 200, await request("PATCH", `/api/maintenance/${state.mainTicketId}/resolve`, {
    token: state.managerToken,
    body: { resolutionNotes: "Replaced failing part.", resolutionCost: 2500 }
  }), (payload) => payload?.data?.status === "RESOLVED" && Boolean(payload?.data?.resolvedAt));

  const dashboardAfterResolve = await request("GET", "/api/dashboard/overview", { token: state.adminToken });
  expectStatus("GET", "/api/dashboard/overview", "Dashboard includes maintenance counters", 200, dashboardAfterResolve, (payload) => typeof payload?.data?.overview?.resolvedTodayMaintenance === "number" && typeof payload?.data?.overview?.inProgressMaintenance === "number");

  expectStatus("PATCH", "/api/maintenance/:id/close", "Manager can close resolved maintenance", 200, await request("PATCH", `/api/maintenance/${state.mainTicketId}/close`, {
    token: state.managerToken,
    body: { resolutionNotes: "Verified after repair." }
  }), (payload) => payload?.data?.status === "CLOSED" && Boolean(payload?.data?.closedAt));
  const assetAfterClose = await request("GET", `/api/assets/${mainAsset.id}`, { token: state.adminToken });
  expectStatus("GET", "/api/assets/:id", "Closing maintenance restores asset state", 200, assetAfterClose, (payload) => payload?.data?.status === "AVAILABLE");
  expectStatus("PATCH", "/api/maintenance/:id", "Closed maintenance cannot be modified", 409, await request("PATCH", `/api/maintenance/${state.mainTicketId}`, {
    token: state.adminToken,
    body: { priority: "LOW" }
  }));
  expectStatus("DELETE", "/api/maintenance/:id", "Closed maintenance cannot be deleted", 409, await request("DELETE", `/api/maintenance/${state.mainTicketId}`, { token: state.adminToken }));

  const rejectAsset = await createAsset(`${stamp}-REJECT`);
  const rejectTicket = await createMaintenance(rejectAsset.id, state.employeeToken, "Reject path issue");
  state.rejectTicketId = rejectTicket.json?.data?.id;
  expectStatus("PATCH", "/api/maintenance/:id/reject", "Admin can reject requested maintenance", 200, await request("PATCH", `/api/maintenance/${state.rejectTicketId}/reject`, {
    token: state.adminToken,
    body: { decisionNotes: "Duplicate request" }
  }), (payload) => payload?.data?.status === "REJECTED");
  const rejectedAssetState = await request("GET", `/api/assets/${rejectAsset.id}`, { token: state.adminToken });
  expectStatus("GET", "/api/assets/:id", "Rejected maintenance restores asset state", 200, rejectedAssetState, (payload) => payload?.data?.status === "AVAILABLE");
  expectStatus("PATCH", "/api/maintenance/:id/assign", "Rejected maintenance cannot be assigned", 409, await request("PATCH", `/api/maintenance/${state.rejectTicketId}/assign`, {
    token: state.adminToken,
    body: { assignedTechnicianId: state.managerId }
  }));
  expectStatus("POST", "/api/maintenance", "Rejected maintenance frees asset for new request", 201, await createMaintenance(rejectAsset.id, state.employeeToken, "New issue after rejection"));

  const deleteAsset = await createAsset(`${stamp}-DELETE`);
  const deleteTicket = await createMaintenance(deleteAsset.id, state.employeeToken, "Delete path issue");
  state.deleteTicketId = deleteTicket.json?.data?.id;
  expectStatus("DELETE", "/api/maintenance/:id", "Admin can delete requested maintenance", 200, await request("DELETE", `/api/maintenance/${state.deleteTicketId}`, { token: state.adminToken }));
  const deletedAssetState = await request("GET", `/api/assets/${deleteAsset.id}`, { token: state.adminToken });
  expectStatus("GET", "/api/assets/:id", "Deleting requested maintenance restores asset state", 200, deletedAssetState, (payload) => payload?.data?.status === "AVAILABLE");

  const closeEarlyAsset = await createAsset(`${stamp}-CLOSE-EARLY`);
  const closeEarlyTicket = await createMaintenance(closeEarlyAsset.id, state.employeeToken, "Close early issue");
  const closeEarlyId = closeEarlyTicket.json?.data?.id;
  await request("PATCH", `/api/maintenance/${closeEarlyId}/approve`, { token: state.managerToken, body: { decisionNotes: "Approved" } });
  expectStatus("PATCH", "/api/maintenance/:id/close", "Approved maintenance cannot close before resolved", 409, await request("PATCH", `/api/maintenance/${closeEarlyId}/close`, {
    token: state.managerToken,
    body: { resolutionNotes: "Too early" }
  }));

  const opsAsset = await createAsset(`${stamp}-OPS`, state.operationsDepartmentId);
  const opsTicket = await createMaintenance(opsAsset.id, state.adminToken, "Operations asset issue");
  state.opsTicketId = opsTicket.json?.data?.id;
  expectStatus("PATCH", "/api/maintenance/:id/approve", "Manager cannot approve another department maintenance", 403, await request("PATCH", `/api/maintenance/${state.opsTicketId}/approve`, {
    token: state.managerToken,
    body: { decisionNotes: "Should fail" }
  }));
  expectStatus("PATCH", "/api/maintenance/:id/approve", "Auditor cannot approve maintenance", 403, await request("PATCH", `/api/maintenance/${state.opsTicketId}/approve`, {
    token: state.auditorToken,
    body: { decisionNotes: "Should fail" }
  }));
  expectStatus("GET", "/api/maintenance/:id", "Employee cannot fetch unrelated maintenance", 403, await request("GET", `/api/maintenance/${state.opsTicketId}`, { token: state.employeeToken }));

  expectStatus("GET", "/api/maintenance", "Maintenance list supports filters", 200, await request("GET", "/api/maintenance?priority=HIGH&status=REQUESTED&page=1&limit=5", { token: state.adminToken }), isPaginated);
  expectStatus("GET", "/api/reports/maintenance", "Maintenance report exposes repair metrics", 200, await request("GET", "/api/reports/maintenance", { token: state.adminToken }), (payload) => typeof payload?.data?.maintenanceCount === "number" && typeof payload?.data?.averageRepairTimeHours === "number" && Array.isArray(payload?.data?.mostRepairedAssets));
  expectStatus("GET", "/api/notifications", "Maintenance notifications are generated", 200, await request("GET", "/api/notifications", { token: state.employeeToken }), (payload) => JSON.stringify(payload).includes("MAINTENANCE_APPROVED") && JSON.stringify(payload).includes("MAINTENANCE_CLOSED"));
  expectStatus("GET", "/api/audit-logs?entityType=MaintenanceTicket", "Maintenance activity logs are generated", 200, await request("GET", "/api/audit-logs?entityType=MaintenanceTicket", { token: state.adminToken }), (payload) => payload?.data?.items?.length >= 7);
};

const main = async () => {
  seedDatabase();
  await runChecks();
  seedDatabase();
  await getSeedContext();
  await refreshMaintenanceResponse();
  writeReport();

  const failed = results.filter((result) => result.result === "FAIL");
  console.log(JSON.stringify({
    summary: {
      total: results.length,
      passed: results.length - failed.length,
      failed: failed.length
    },
    failed
  }, null, 2));

  await prisma.$disconnect();
  if (failed.length > 0) process.exit(1);
};

main().catch(async (error) => {
  console.error(error);
  await prisma.$disconnect();
  process.exit(1);
});
