import { Router } from "express";
import { allocationRoutes } from "./allocationRoutes.js";
import { assetRoutes } from "./assetRoutes.js";
import { auditLogRoutes, auditRoutes } from "./auditRoutes.js";
import { authRoutes } from "./authRoutes.js";
import { bookingRoutes } from "./bookingRoutes.js";
import { dashboardRoutes } from "./dashboardRoutes.js";
import { categoryRoutes, departmentRoutes, userRoutes } from "./referenceRoutes.js";
import { maintenanceRoutes } from "./maintenanceRoutes.js";
import { notificationRoutes } from "./notificationRoutes.js";
import { organizationRoutes } from "./organizationRoutes.js";
import { reportRoutes } from "./reportRoutes.js";
import { settingsRoutes } from "./settingsRoutes.js";
import { transferRoutes } from "./transferRoutes.js";

export const apiRoutes = Router();

apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/users", userRoutes);
apiRoutes.use("/departments", departmentRoutes);
apiRoutes.use("/categories", categoryRoutes);
apiRoutes.use("/assets", assetRoutes);
apiRoutes.use("/allocations", allocationRoutes);
apiRoutes.use("/transfers", transferRoutes);
apiRoutes.use("/bookings", bookingRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
apiRoutes.use("/maintenance", maintenanceRoutes);
apiRoutes.use("/audits", auditRoutes);
apiRoutes.use("/audit-logs", auditLogRoutes);
apiRoutes.use("/reports", reportRoutes);
apiRoutes.use("/notifications", notificationRoutes);
apiRoutes.use("/organization", organizationRoutes);
apiRoutes.use("/settings", settingsRoutes);
