ALTER TYPE "MaintenanceStatus" ADD VALUE IF NOT EXISTS 'REQUESTED';
ALTER TYPE "MaintenanceStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "MaintenanceStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
